# Generated by Django 6.1.1 on 2026-09-29 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='twogis_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на кинотеатр в 2ГИС (например: https://2gis.kg/bishkek/firm/...)', verbose_name='Ссылка на 2ГИС'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры карты'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Базовая — 500 сом/мес'), ('premium', 'Премиум — 1200 сом/мес'), ('vip', 'VIP — 2500 сом/мес')], default='basic', max_length=20, verbose_name='Тариф')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20, verbose_name='Тариф')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('card_last4', models.CharField(max_length=4, verbose_name='Последние 4 цифры')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код транзакции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата подписки',
                'verbose_name_plural': 'Оплаты подписок',
                'ordering': ['-paid_at'],
            },
        ),
    ]
