# Generated by Django 6.1.1 on 2026-09-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_cinema_description_cinema_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию здания или зала', null=True, upload_to='cinemas/', verbose_name='Фото кинотеатра'),
        ),
    ]
